# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

version: 2

project_name: ecsdeployer

before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows

    goarch:
      # - "386"
      - amd64
      # - arm
      - arm64

    # goarm:
    #   - "7"

    flags:
      - "-trimpath"

    ldflags:
      - "-s -w"
      - -X ecsdeployer.com/ecsdeployer/pkg/version.Version={{.Version}}
      - -X ecsdeployer.com/ecsdeployer/pkg/version.BuildSHA={{.FullCommit}}
      - -X ecsdeployer.com/ecsdeployer/pkg/version.ShortSHA={{.ShortCommit}}
      - -X ecsdeployer.com/ecsdeployer/pkg/version.Prerelease={{.Prerelease}}

archives:
  - id: homebrew
    format_overrides:
      - goos: linux
        formats: ['tar.gz']
      - goos: windows
        formats: ['zip']
    name_template: '{{ .ProjectName }}_{{- tolower .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}{{- if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Version }}"

release:
  footer: |
    **Full Changelog**: https://github.com/ecsdeployer/ecsdeployer/compare/{{ .PreviousTag }}...{{ .Tag }}

changelog:
  disable: true

announce:
  skip: true

universal_binaries:
  - name_template: "{{ .ProjectName }}"
    replace: false

source:
  enabled: true

sboms:
  - artifacts: archive
  - id: source # Two different sbom configurations need two different IDs
    artifacts: source

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes" # needed on cosign 2.0.0+
    artifacts: checksum
    output: true

scoops:
  - repository:
      owner: ecsdeployer
      name: scoop-bucket
      token: "{{ .Env.HOMEBREW_SCOOP_GITHUB_TOKEN }}"
    url_template: "https://github.com/ecsdeployer/ecsdeployer/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: cloud87bot
      email: 114977785+cloud87bot@users.noreply.github.com
    homepage:  https://ecsdeployer.com
    description: Easily deploy containerized applications to AWS ECS Fargate
    license: MIT

homebrew_casks:

  - &hbgen
    ids:
      - homebrew
    name: ecsdeployer
    repository:
      owner: ecsdeployer
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_SCOOP_GITHUB_TOKEN }}"
    url:
      template: "https://github.com/ecsdeployer/ecsdeployer/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://ecsdeployer.com"
    description: "Easily deploy containerized applications to AWS ECS Fargate"
    skip_upload: auto
    commit_author:
      name: cloud87bot
      email: 114977785+cloud87bot@users.noreply.github.com
    binaries:
      - ecsdeployer
    completions:
      bash: completions/ecsdeployer.bash
      fish: completions/ecsdeployer.fish
      zsh: completions/ecsdeployer.zsh
    manpages:
      - manpages/ecsdeployer.1.gz
    hooks:
      post:
        install: |
          system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ecsdeployer"]

  -
    << : *hbgen
    name: ecsdeployer@v{{ .Major }}

nfpms:
  - id: "ecsdeployer"
    ids: ['ecsdeployer']
    formats:
      - deb
      - rpm
      - apk
    vendor: "ecsdeployer.com"
    homepage: "https://ecsdeployer.com/"
    maintainer: "Mitch Dempsey <webdestroya@noreply.github.com>"
    description: "Easily deploy containerized applications to AWS ECS Fargate"
    file_name_template: "{{ .ConventionalFileName }}"
    license: MIT
    bindir: /usr/bin
    section: utils
    rpm:
      summary: "Easily deploy containerized applications to AWS ECS Fargate"
    contents:
      - src: ./completions/ecsdeployer.bash
        dst: /usr/share/bash-completion/completions/ecsdeployer
        file_info:
          mode: 0644
      - src: ./completions/ecsdeployer.fish
        dst: /usr/share/fish/vendor_completions.d/ecsdeployer.fish
        file_info:
          mode: 0644
      - src: ./completions/ecsdeployer.zsh
        dst:  /usr/share/zsh/vendor-completions/_ecsdeployer
        file_info:
          mode: 0644
      - src: ./manpages/ecsdeployer.1.gz
        dst: /usr/share/man/man1/ecsdeployer.1.gz
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/ecsdeployer/copyright
        file_info:
          mode: 0644

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
