name: Docs Release

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  
jobs:
  docs:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: .go-version

      - name: Run Docs Helper Scripts
        run: ./scripts/cmd_docs.sh
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install mkdocs and deps
        run: pip install -r www/requirements.txt
        
      - name: Deploy Docs
        working-directory: ./www
        run: mkdocs gh-deploy --clean --remote-branch gh-pages --no-history