name: Docs Test

on:
  workflow_call:

  push:
    branches:
      - 'main'
    paths:
      - 'www/*'
  pull_request:
    paths:
      - 'www/*'

permissions:
  contents: read
  
jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: .go-version

      - name: Run Docs Helper Scripts
        run: ./scripts/cmd_docs.sh
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install mkdocs and deps
        run: pip install -r www/requirements.txt

      - name: Build Site
        working-directory: ./www
        run: mkdocs build
      
      - uses: wjdp/htmltest-action@09118714cd26bef56bd3d0819e4f9b1dce6f60a9 # master
        with:
          path: www/site
          config: www/htmltest.yml