name: golangci-lint Checks

on:
  push:
    branches:
      - main
      - exploration
      - 'release/**'
  pull_request:
    paths:
      - .github/workflows/lint.yml
      - .go-version
      - .tool-versions
      - .golangci.yml
      - internal/**
      - cmd/**
      - pkg/**
      - go.sum
      - main.go

permissions:
  contents: read

jobs:
  golangci:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: .go-version

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          install-mode: binary
          version-file: .tool-versions
          args: --config .golangci.yml --timeout 5m --verbose
      
  