name: Test Suite
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/test.yml
      - .go-version
      - cmd/**
      - internal/**
      - go.sum
      - main.go
      - pkg/**
      - scripts/**
jobs:
  testsuite:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: .go-version
      
      - name: Install Task
        uses: go-task/setup-task@v1
        with:
          version: 3.x

      - name: Run CLI Unit Tests
        run: |
          go clean -testcache
          task test